version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  messenger-server:
    type: boolean
    default: false
  messenger-client-cli:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/golang:1.14.3

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  checkout:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  test:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content to test
          command: echo "Run tests << parameters.package_name >> ..." && go test -v -trimpath -race -vet all ./...

  build:
    parameters:
      package_name:
        type: string
      main_path:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content 
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..." && CGO_ENABLED=0 go build -o ./app << parameters.main_path >>
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  messenger-server:
    when: << pipeline.parameters.messenger-server >>
    jobs:
      - checkout:
          name: messenger-server-checkout
          package_name: messenger-server
      - test:
          name: messenger-server-test
          package_name: messenger-server
          requires:
            - messenger-server-checkout
      - build:
          name: messenger-server-build
          package_name: messenger-server
          main_path: ./cmd/server
          requires:
            - messenger-server-test
      - deploy:
          name: messenger-server-deploy
          package_name: messenger-server
          requires:
            - messenger-server-test

  messenger-client-cli:
    when: << pipeline.parameters.messenger-client-cli >>
    jobs:
      - checkout:
          name: messenger-client-cli-checkout
          package_name: messenger-client-cli
      - test:
          name: messenger-client-cli-test
          package_name: messenger-client-cli
          requires:
            - messenger-client-cli-checkout
      - build:
          name: messenger-client-cli-build
          package_name: messenger-client-cli
          main_path: ./cmd/cli
          requires:
            - messenger-client-cli-test
      - deploy:
          name: messenger-client-cli-deploy
          package_name: messenger-client-cli
          requires:
            - messenger-client-cli-test