version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  messenger-server:
    type: boolean
    default: false
  messenger-client-cli:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/golang:1.14.3

orbs:
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  checkout:
    parameters:
      package_name:
        type: string
    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  lint:
    parameters:
      package_name:
        type: string
    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Download linter
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run:
          name: Lint
          command: golangci-lint run ./...

  test:
    parameters:
      package_name:
        type: string
    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content to test
          command: echo "Run tests << parameters.package_name >> ..." && go test -v -trimpath -race -vet all ./...

  build:
    parameters:
      package_name:
        type: string
      main_path:
        type: string
    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - run:
          name: Content 
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..." && CGO_ENABLED=0 go build -o ./app << parameters.main_path >>
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  docker-build-publish:
    parameters:
      package_name:
        type: string
    working_directory: ~/project/packages/<< parameters.package_name >>
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build and push Docker image
          command: |
            export TAG=$(cat version.txt)-$CIRCLE_BUILD_NUM
            export IMAGE_NAME=<< parameters.package_name >>
            docker build -t ankura22/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ankura22/$IMAGE_NAME:$TAG

  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    parameters:
      package_name:
        type: string
    working_directory: ~/project/packages/<< parameters.package_name >>
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - gcr/gcr-auth
      - gcr/build-image:
          image: ankura22/<< parameters.package_name >>
          tag: "$(cat version.txt)-$CIRCLE_BUILD_NUM"
      - gcr/push-image:
          image: ankura22/<< parameters.package_name >>
          tag: "$(cat version.txt)-$CIRCLE_BUILD_NUM"

  Deploy-GCP:
    description: Deploy application to Google Kubernetes Engine
    parameters:
      package_name:
        type: string
    working_directory: ~/project/packages/<< parameters.package_name >>
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - gcr/gcr-auth
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          deployment: messenger
          cluster: messenger-cluster
          container: messenger-server
          image: gcr.io/messenger-server-279013/ankura22/<< parameters.package_name >>
          tag: "$(cat version.txt)-215"
          # image: gcr.io/ankura22/<< parameters.package_name >>:$(cat version.txt)-$CIRCLE_BUILD_NUM

  deploy:
    parameters:
      package_name:
        type: string
    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  messenger-server:
    when: << pipeline.parameters.messenger-server >>
    jobs:
      - checkout:
          name: messenger-server-checkout
          package_name: messenger-server
      # - lint:
      #     name: messenger-server-lint
      #     package_name: messenger-server
      #     requires:
      #       - messenger-server-checkout
      # - test:
      #     name: messenger-server-test
      #     package_name: messenger-server
      #     requires:
      #       - messenger-server-checkout
      - build:
          name: messenger-server-build
          package_name: messenger-server
          main_path: ./cmd/server
          requires:
            # - messenger-server-lint
            # - messenger-server-test
            - messenger-server-checkout
      # - docker-build-publish:
      #     name: messenger-server-docker-build-publish
      #     package_name: messenger-server
      #     requires:
      #       - messenger-server-build
      # - Build-Push-Image-Docker:
      #     name: messenger-server-Build-Push-Image-Docker
      #     package_name: messenger-server
      #     requires:
      #       - messenger-server-build
      - Deploy-GCP:
          name: messenger-server-Deploy-GCP
          package_name: messenger-server
          requires:
            - messenger-server-build
            # - messenger-server-Build-Push-Image-Docker

  messenger-client-cli:
    when: << pipeline.parameters.messenger-client-cli >>
    jobs:
      - checkout:
          name: messenger-client-cli-checkout
          package_name: messenger-client-cli
      - lint:
          name: messenger-client-cli-lint
          package_name: messenger-client-cli
          requires:
            - messenger-client-cli-checkout
      - test:
          name: messenger-client-cli-test
          package_name: messenger-client-cli
          requires:
            - messenger-client-cli-checkout
      - build:
          name: messenger-client-cli-build
          package_name: messenger-client-cli
          main_path: ./cmd/cli
          requires:
            - messenger-client-cli-lint
            - messenger-client-cli-test
      - deploy:
          name: messenger-client-cli-deploy
          package_name: messenger-client-cli
          requires:
            - messenger-client-cli-build