apiVersion: apps/v1
kind: Deployment
metaData:
  name: {{ template "messenger-server.fullname" . }}
  labels:
    app: {{ template "messenger-server.name" . }}
    chart: {{ template "messenger-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "messenger-server.name" . }}
      release: {{ .Release.Name }}
      tier: backend
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "messenger-server.name" . }}
        release: {{ .Release.Name }}
        tier: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - curl localhost:{{ .Values.service.httpPort }}
            initialDelaySeconds: 1
            timeoutSeconds: 5
          env:
            - name: PORT
              value: {{ .Values.env.port }}
