{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "messenger-server.fullname" . }}
  labels:
    app: {{ template "messenger-server.name" . }}
    chart: {{ template "messenger-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "messenger-server.name" . }}
    release: {{ .Release.Name }}
    tier: backend
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
